# Generated by Django 3.2.18 on 2025-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Requête en langage naturel')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('generated_code', models.TextField(blank=True, null=True)),
                ('execution_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
